### ISSUE TITLE
feature request: accept a yaml string from stdin

### ISSUE THREAD

**Issue by miketheman** [lucasepe/yml2dot#1]
Learned about this project recently, very cool!

In combining with other unix-style commands, I'd love to be able to pipe in a well-formed YAML file as an input, rather than a file, like so:

```shell
cat foo.yaml | yml2dot | dot -Tpng ....
```

In this example, I have a real yaml file, but I can imagine where I may emit a YAML from some other program to STDOUT, to have another process read it from STDIN.

**Comment by lucasepe** [comment]
Hi @miketheman thank you and sorry for the very late response, I have only now seen your issue.

Yes ! This is in my backlog and I'll do it  in a few weeks.

**Comment by miketheman** [comment]
No problem, thanks for taking it on!
